---
name: "Celian incident 37312"

on:
  push

jobs:
  release-note-check:
    if: github.triggering_actor != 'dd-devflow[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version-file: .python-version
          cache: 'pip'
          cache-dependency-path: '.dda/version'
      - name: Install dda
        uses: ./.github/actions/install-dda
        with:
          features: legacy-tasks
      - name: Test
        run: |
          ls -la ~/.cache
